"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path

try:
    from decouple import config  # type: ignore
except ImportError:
    def config(key, default=None, cast=None):
        import os
        value = os.getenv(key, default)
        if cast:
            return cast(value)
        return value

# dj_database_url is optional in some environments (linting/IDE may warn if not installed).
# Import it if available, otherwise provide a minimal fallback to support local SQLite
# when DATABASE_URL is not provided.
try:
    import dj_database_url  # type: ignore
except Exception:  # pragma: no cover - fallback for environments without the package
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Read secret values securely from your local .env file
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

# Allow local testing and your future live Render domain
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    # Cloudinary storage needs to sit right before staticfiles
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    
    # Custom Application App
    'albums',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Added templates directory root mapping
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database Configuration
# Automatically switches between SQLite locally and PostgreSQL on Render
if dj_database_url is not None:
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL', default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'))
        )
    }
else:
    # Fallback to a simple SQLite config when dj_database_url is not available.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Cloudinary Integration API Storage Settings
# ==============================================================================
# ==============================================================================

try:
    import cloudinary  # type: ignore
except Exception:
    cloudinary = None

# 1. Configure the Cloudinary credentials safely
if cloudinary is None:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "The 'cloudinary' package is required but not installed. Install it via 'pip install cloudinary'."
    )

cloudinary.config(
    cloud_name = config('CLOUDINARY_CLOUD_NAME'),
    api_key = config('CLOUDINARY_API_KEY'),
    api_secret = config('CLOUDINARY_API_SECRET'),
    secure = True
)

# 2. Tell Django to use Cloudinary for uploaded files
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Use Python's f-string to construct the URL securely from environment variables
CLOUDINARY_STORAGE = {
    'CLOUDINARY_URL': f"cloudinary://{config('CLOUDINARY_API_KEY')}:{config('CLOUDINARY_API_SECRET')}@{config('CLOUDINARY_CLOUD_NAME')}"
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Standard redirects for our Authentication flow
LOGIN_REDIRECT_URL = 'album-list'
LOGOUT_REDIRECT_URL = 'album-list'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'